# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf641f4167fb09a41b92d4e0d7f0563e08c4a0f38b8344a1c264e71bd8c909e77770d7baf37e947aebe184c74e4d53c5e219764341065ccb0eeb2bbd3d0b4906

test:
  secret_key_base: ccc1ded635cd9c78c5148336e559577330a5bcd77fd3286ded6895b954f3fbe0a164c57b6a664edc1c22ddc8ef5c4a1b8797bec84bdaa1820e43a6e211cb4f20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
